{
 "title": "Dashboard 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voltage Vback (mV)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads1_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Signal status 0 (mV)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads2_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Signal status 1 (mV)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads3_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Signal status 2 (mV)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads4_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Source voltage (mV)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina1_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Сapacitor voltage (mV)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina2_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "LOAD voltage (mV)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina3_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "nRF  voltage (mV)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina4_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Source current (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina1_current{instance=\"localhost:8000\"}"
    }
   ]
  },
  {
   "title": "Capacitor current (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina2_current{instance=\"localhost:8000\"}"
    }
   ]
  },
  {
   "title": "LOAD current  (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina3_current{instance=\"localhost:8000\"}"
    }
   ]
  },
  {
   "title": "nRF current (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina4_current{instance=\"localhost:8000\"}"
    }
   ]
  },
  {
   "title": "nRF Ch 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ina4_current{instance=\"localhost:8000\"}",
     "legendFormat": "Current Ch 4(mA)"
    },
    {
     "expr": "ina4_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage Ch4(mV)"
    }
   ]
  },
  {
   "title": "Sim Ch 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ina5_current{instance=\"localhost:8000\"}",
     "legendFormat": "Current Ch 5(mA)"
    },
    {
     "expr": "ina5_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage Ch5(mV)"
    }
   ]
  },
  {
   "title": "Sim  voltage (mV)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina5_voltage{instance=\"localhost:8000\"} * 1000"
    }
   ]
  },
  {
   "title": "Sim current (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ina5_current{instance=\"localhost:8000\"}"
    }
   ]
  },
  {
   "title": "5 channels (Current mA/Voltage mV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ina1_current{instance=\"localhost:8000\"}",
     "legendFormat": "Source current(mA) Ch 1"
    },
    {
     "expr": "ina2_current{instance=\"localhost:8000\"}",
     "legendFormat": "Capacitor current(mA) Ch2"
    },
    {
     "expr": "ina3_current{instance=\"localhost:8000\"}",
     "legendFormat": "HV current(mA) Ch3"
    },
    {
     "expr": "ina4_current{instance=\"localhost:8000\"}",
     "legendFormat": "LV current(mA) Ch4"
    },
    {
     "expr": "ina1_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Source voltage(mV) Ch1"
    },
    {
     "expr": "ina2_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Capacitor voltage(mV) Ch2"
    },
    {
     "expr": "ina3_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "HV voltage(mV) Ch3"
    },
    {
     "expr": "ina4_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "LV voltage(mV) Ch4"
    },
    {
     "expr": "ads1_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Vbuck signal(mV) ADS_Ch1"
    },
    {
     "expr": "ads2_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Status 0 signal(mV) ADS_Ch2"
    },
    {
     "expr": "ads3_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Status 1 signal(mV) ADS_Ch3"
    },
    {
     "expr": "ads4_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Status 2 signal(mV) ADS_Ch4"
    }
   ]
  },
  {
   "title": "Source Ch 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ina1_current{instance=\"localhost:8000\"}",
     "legendFormat": "Current Ch1(mA)"
    },
    {
     "expr": "ina1_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage Ch1(mV)"
    }
   ]
  },
  {
   "title": "Capacitor Ch 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "ina2_current{instance=\"localhost:8000\"}",
     "legendFormat": "Current Ch 2(mA)"
    },
    {
     "expr": "ina2_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage Ch 2(mV)"
    }
   ]
  },
  {
   "title": "LOAD Ch 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "ina3_current{instance=\"localhost:8000\"}",
     "legendFormat": "Current Ch 3(mA)"
    },
    {
     "expr": "ina3_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage Ch3(mV)"
    }
   ]
  },
  {
   "title": "Vbuck Ads Ch 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "ads1_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage (mV)"
    }
   ]
  },
  {
   "title": "Status 0 Ads Ch 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "ads2_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage (mV)"
    }
   ]
  },
  {
   "title": "Status 2 Ads Ch 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "ads4_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage (mV)"
    }
   ]
  },
  {
   "title": "Status 1 Ads Ch 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "ads3_voltage{instance=\"localhost:8000\"} * 1000",
     "legendFormat": "Voltage (mV)"
    }
   ]
  }
 ]
}